ALTER TABLE item
    ALTER COLUMN mc TYPE NUMERIC(10,2) USING NULLIF(mc::text, 'false')::numeric,
    ALTER COLUMN hc TYPE NUMERIC(10,2) USING NULLIF(hc::text, 'false')::numeric;

ALTER TABLE item
    ALTER COLUMN mc TYPE NUMERIC(10,2) USING NULL,
    ALTER COLUMN hc TYPE NUMERIC(10,2) USING NULL;